// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMv0xpDjliUuQes7dMl2KY9QlovE9urnA',
    appId: '1:428003320486:web:401c827baa34a43fc40a67',
    messagingSenderId: '428003320486',
    projectId: 'ncu-service-test',
    authDomain: 'ncu-service-test.firebaseapp.com',
    storageBucket: 'ncu-service-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMakWbjUOtyhQyVxwmSgTOri1dXMNOt10',
    appId: '1:428003320486:android:3165958c2836e7cbc40a67',
    messagingSenderId: '428003320486',
    projectId: 'ncu-service-test',
    storageBucket: 'ncu-service-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdyOd6bFlYcWtTBukPVa9jcSiTWI7cQc',
    appId: '1:428003320486:ios:cb0939194453bbd7c40a67',
    messagingSenderId: '428003320486',
    projectId: 'ncu-service-test',
    storageBucket: 'ncu-service-test.appspot.com',
    iosClientId: '428003320486-rgcp4m50egch5u6e9u80pla2edrga81e.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFdyOd6bFlYcWtTBukPVa9jcSiTWI7cQc',
    appId: '1:428003320486:ios:cb0939194453bbd7c40a67',
    messagingSenderId: '428003320486',
    projectId: 'ncu-service-test',
    storageBucket: 'ncu-service-test.appspot.com',
    iosClientId: '428003320486-rgcp4m50egch5u6e9u80pla2edrga81e.apps.googleusercontent.com',
    iosBundleId: 'com.example.theBasics',
  );
}
